ratingAlc.searchByFilter=select r from RatingAlcolico\

ordine.searchWithParameters=SELECT DISTINCT o \
  FROM Ordine o \
  WHERE (:data IS NULL OR o.data_ordine = :data) \
    AND (:totale IS NULL OR o.totale = :totale) \
    AND (:id_status IS NULL OR o.status.id = :id_status) \
    AND (:id_utente IS NULL OR o.utente.id = :id_utente) \
    AND (:indirizzo_destinazione IS NULL OR o.indirizzoDestinazione LIKE CONCAT(:indirizzo_destinazione, '%')) \
    
    
ordineAlcolico.searchWithParameters=SELECT DISTINCT oa \
  FROM OrdineAlcolico oa \
  WHERE (:quantita IS NULL OR oa.quantita = :quantita) \
    AND (:id_ordine IS NULL OR oa.ordine.id = :id_ordine) \
    AND (:id_status IS NULL OR oa.status.id = :id_status) \
    AND (:id_alcolico IS NULL OR oa.alcolico.id = :id_alcolico) \
    AND (:id_cantina IS NULL OR oa.cantina.id = :id_cantina) \
    
    
status.searchWithParameters=SELECT DISTINCT s \
  FROM Status s \
  WHERE (:nome IS NULL OR s.nome LIKE CONCAT(:nome, '%')) \
    AND (:descrizione IS NULL OR s.descrizione LIKE CONCAT(:descrizione, '%'))