ratingAlc.searchByFilter=select r from RatingAlcolico\

ordine.searchWithParameters=SELECT DISTINCT o \
  FROM Ordine o \
  WHERE (:data IS NULL OR o.data_ordine = :data) \
    AND (:totale IS NULL OR o.totale = :totale) \
    AND (:id_status IS NULL OR o.status.id = :id_status) \
    AND (:id_utente IS NULL OR o.utente.id = :id_utente) \
    AND (:indirizzo_destinazione IS NULL OR o.indirizzoDestinazione LIKE CONCAT(:indirizzo_destinazione, '%')) \
    
    
ordineAlcolico.searchWithParameters=SELECT DISTINCT oa \
  FROM OrdineAlcolico oa \
  WHERE (:quantita IS NULL OR oa.quantita = :quantita) \
    AND (:id_ordine IS NULL OR oa.ordine.id = :id_ordine) \
    AND (:id_status IS NULL OR oa.status.id = :id_status) \
    AND (:id_alcolico IS NULL OR oa.alcolico.id = :id_alcolico) \
    AND (:id_cantina IS NULL OR oa.cantina.id = :id_cantina) \
    
    
status.searchWithParameters=SELECT DISTINCT s \
  FROM Status s \
  WHERE (:nome IS NULL OR s.nome LIKE CONCAT(:nome, '%')) \
    AND (:descrizione IS NULL OR s.descrizione LIKE CONCAT(:descrizione, '%'))
    
spedizioneAlcolico.searchWithParameters=SELECT DISTINCT sa \
  FROM SpedizioneAlcolico sa \
  WHERE (:corriere IS NULL OR sa.corriere LIKE CONCAT(:corriere, '%')) \
    AND (:codice_tracciamento IS NULL OR sa.codice_tracciamento LIKE CONCAT(:codice_tracciamento, '%')) \
    AND (:id_cantina IS NULL OR sa.cantina.id = :id_cantina) \
    AND (:id_cliente IS NULL OR sa.cliente.id = :id_cliente) \
    AND (:id_status IS NULL OR sa.status.id = :id_status) \
    AND (:id_ordine_alcolico IS NULL OR sa.ordineAlcolico.id = :id_ordine_alcolico)
    
spedizioneBox.searchWithParameters=SELECT DISTINCT sb \
  FROM SpedizioneBox sb \
  WHERE (:corriere IS NULL OR sb.corriere LIKE CONCAT(:corriere, '%')) \
    AND (:codice_tracciamento IS NULL OR sb.codice_tracciamento LIKE CONCAT(:codice_tracciamento, '%')) \
    AND (:id_cantina IS NULL OR sb.cantina.id = :id_cantina) \
    AND (:id_cliente IS NULL OR sb.cliente.id = :id_cliente) \
    AND (:id_status IS NULL OR sb.status.id = :id_status) \
    AND (:id_ordine_box IS NULL OR sb.ordineBox.id = :id_ordine_box)
    
    boxalc.searchByFilter= select 