ratingAlc.searchByFilter=SELECT r FROM RatingAlcolico r\
WHERE (:alcolico IS NULL OR r.alcolico.nome = :alcolico%)\
AND (:utente IS NULL OR r.utente.id = :utente)\
AND (:valutazione IS NULL OR r.valutazione = :valutazione)

ratingCant.searchByFilter=SELECT r FROM RatingCantina r\
WHERE (:cantina IS NULL OR r.cantina.nome = :cantina%)\
AND (:utente IS NULL OR r.utente.id = :utente)\
AND (:valutazione IS NULL OR r.valutazione = :valutazione)