ratingAlc.searchByFilter=SELECT r FROM RatingAlcolico r \
WHERE (:alcolico IS NULL OR r.alcolico.id = :alcolico) \
AND (:utente IS NULL OR r.utente.id = :utente) \
AND (:valutazione IS NULL OR r.valutazione = :valutazione)

ratingCant.searchByFilter=SELECT r FROM RatingCantina r \
WHERE (:cantina IS NULL OR r.cantina.id = :cantina) \
AND (:utente IS NULL OR r.utente.id = :utente) \
AND (:valutazione IS NULL OR r.valutazione = :valutazione)