
    create table alcolico (
        annata integer,
        gradazione integer,
        id integer generated by default as identity,
        id_colore integer,
        id_tipologia_alcolico integer,
        id_venditore integer,
        prezzo float(53),
        descrizione varchar(255),
        nome varchar(255),
        provenienza varchar(255),
        primary key (id)
    );

    create table alcolico_caratteristica (
        id_alcolico integer not null,
        id_caratteristica integer not null
    );

    create table box (
        id integer generated by default as identity,
        id_cantina integer,
        sconto float(53),
        nome varchar(255) not null,
        primary key (id)
    );

    create table box_alcolico (
        id integer generated by default as identity,
        id_alcolico integer,
        id_box integer,
        quantita integer not null,
        primary key (id)
    );

    create table cantina (
        id integer generated by default as identity,
        id_posizione integer unique,
        id_venditore integer,
        nome varchar(255) not null,
        primary key (id)
    );

    create table cantina_alcolico (
        id integer generated by default as identity,
        id_alcolico integer,
        id_cantina integer,
        quantita integer not null,
        primary key (id)
    );

    create table caratteristica (
        id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table carrello (
        id integer generated by default as identity,
        id_cliente integer unique,
        quantita integer not null,
        totale float(53) not null,
        primary key (id)
    );

    create table cliente (
        id integer generated by default as identity,
        id_carrello integer unique,
        id_utente integer unique,
        indirizzo varchar(255) not null,
        primary key (id)
    );

    create table colore (
        id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table degustazione (
        id integer generated by default as identity,
        id_cantina integer,
        prezzo float(53) not null,
        data_fine timestamp(6) not null,
        data_inizio timestamp(6) not null,
        descrizione varchar(255),
        nome varchar(255) not null,
        primary key (id)
    );

    create table degustazione_alcolico (
        id_alcolico integer not null,
        id_degustazione integer not null
    );

    create table immagine_alcolico (
        id integer generated by default as identity,
        id_alcolico integer,
        url varchar(255) not null,
        primary key (id)
    );

    create table immagine_box (
        id integer generated by default as identity,
        id_box integer,
        url varchar(255) not null,
        primary key (id)
    );

    create table immagine_cantina (
        id integer generated by default as identity,
        id_cantina integer,
        url varchar(255) not null,
        primary key (id)
    );

    create table immagine_degustazione (
        id integer generated by default as identity,
        id_degustazione integer,
        url varchar(255) not null,
        primary key (id)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(50) not null,
        messaggio varchar(255),
        primary key (lang, code)
    );

    create table ordine (
        data_ordine date not null,
        id integer generated by default as identity,
        status integer,
        totale float(53) not null,
        utente integer,
        indirizzo_destinazione varchar(255) not null,
        primary key (id)
    );

    create table ordine_alcolico (
        cantina integer,
        id integer generated by default as identity,
        id_alcolico integer,
        id_ordine integer,
        quantita integer not null,
        status integer,
        primary key (id)
    );

    create table ordine_box (
        cantina integer,
        id integer generated by default as identity,
        id_box integer,
        id_ordine integer,
        quantita integer not null,
        status integer,
        primary key (id)
    );

    create table ordine_degustazione (
        cantina integer,
        id integer generated by default as identity,
        id_degustazione integer,
        id_ordine integer,
        quantita integer not null,
        status integer,
        primary key (id)
    );

    create table posizione (
        id integer generated by default as identity,
        latitudine float(53) not null,
        longitudine float(53) not null,
        descrizione varchar(255),
        primary key (id)
    );

    create table prenotazione_degustazione (
        cantina integer,
        id integer generated by default as identity,
        id_degustazione integer,
        id_ordine integer,
        status integer,
        primary key (id)
    );

    create table prodotto_alcolico (
        id integer generated by default as identity,
        id_alcolico integer,
        id_cantina integer,
        id_carrello integer,
        quantita integer not null,
        primary key (id)
    );

    create table prodotto_box (
        id integer generated by default as identity,
        id_box integer,
        id_cantina integer,
        id_carrello integer,
        quantita integer not null,
        primary key (id)
    );

    create table prodotto_degustazione (
        id integer generated by default as identity,
        id_cantina integer,
        id_carrello integer,
        id_degustazione integer,
        quantita integer not null,
        primary key (id)
    );

    create table rating_alcolico (
        id integer generated by default as identity,
        id_alcolico integer,
        id_cantina integer,
        id_cliente integer,
        valutazione float(53) not null,
        commento varchar(255) not null,
        primary key (id)
    );

    create table rating_cantina (
        id integer generated by default as identity,
        id_cantina integer,
        id_cliente integer,
        valutazione float(53) not null,
        commento varchar(255) not null,
        primary key (id)
    );

    create table role (
        can_buy boolean not null,
        can_manage boolean not null,
        can_sell boolean not null,
        id integer generated by default as identity,
        nome varchar(100) not null,
        primary key (id)
    );

    create table spedizione_alcolico (
        id integer generated by default as identity,
        id_cantina integer,
        id_cliente integer,
        id_ordine_alcolico integer unique,
        status integer unique,
        codice_tracciamento varchar(255) not null,
        corriere varchar(255) not null,
        primary key (id)
    );

    create table spedizione_box (
        id integer generated by default as identity,
        id_cantina integer,
        id_cliente integer,
        status integer unique,
        codice_tracciamento varchar(255) not null,
        corriere varchar(255) not null,
        primary key (id)
    );

    create table status (
        id integer generated by default as identity,
        descrizione varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table tipologia_alcolico (
        id integer generated by default as identity,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table utente (
        data_nascita date not null,
        id integer generated by default as identity,
        id_ruolo integer,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        email varchar(255) not null unique,
        password varchar(255) not null,
        primary key (id)
    );

    create table venditore (
        id integer generated by default as identity,
        id_utente integer unique,
        partita_iva varchar(255) not null,
        primary key (id)
    );

    alter table if exists alcolico 
       add constraint fk_alcolico_colore 
       foreign key (id_colore) 
       references colore;

    alter table if exists alcolico 
       add constraint fk_alcolico_tipologia 
       foreign key (id_tipologia_alcolico) 
       references tipologia_alcolico;

    alter table if exists alcolico 
       add constraint fk_alcolico_venditore 
       foreign key (id_venditore) 
       references venditore;

    alter table if exists alcolico_caratteristica 
       add constraint FKek22r3y74kgayspy92pfkcw0s 
       foreign key (id_caratteristica) 
       references caratteristica;

    alter table if exists alcolico_caratteristica 
       add constraint FK4jw36v1f6q4369nphoka9o4vq 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists box 
       add constraint fk_box_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists box_alcolico 
       add constraint fk_boxAlcolico_alcolico 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists box_alcolico 
       add constraint fk_boxAlcolico_box 
       foreign key (id_box) 
       references box;

    alter table if exists cantina 
       add constraint fk_cantina_posizione 
       foreign key (id_posizione) 
       references posizione;

    alter table if exists cantina 
       add constraint fk_cantina_venditore 
       foreign key (id_venditore) 
       references venditore;

    alter table if exists cantina_alcolico 
       add constraint fk_cantina_alcolico_bottiglia 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists cantina_alcolico 
       add constraint fk_cantina_alcolico 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists carrello 
       add constraint fk_carrello_cliente 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists cliente 
       add constraint fk_cliente_carrello 
       foreign key (id_carrello) 
       references carrello;

    alter table if exists cliente 
       add constraint fk_utente_cliente 
       foreign key (id_utente) 
       references utente;

    alter table if exists degustazione 
       add constraint fk_degustazione_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists degustazione_alcolico 
       add constraint FKpwbgxed2q41fl12cxr1qh501c 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists degustazione_alcolico 
       add constraint FKglcsfyqrpma7jss24wbc9krmq 
       foreign key (id_degustazione) 
       references degustazione;

    alter table if exists immagine_alcolico 
       add constraint fk_immagine_alcolico 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists immagine_box 
       add constraint fk_immagine_box 
       foreign key (id_box) 
       references box;

    alter table if exists immagine_cantina 
       add constraint fk_immagine_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists immagine_degustazione 
       add constraint fk_immagine_degustazione 
       foreign key (id_degustazione) 
       references degustazione;

    alter table if exists ordine 
       add constraint fk_ordine_status 
       foreign key (status) 
       references status;

    alter table if exists ordine 
       add constraint fk_ordine_utente 
       foreign key (utente) 
       references utente;

    alter table if exists ordine_alcolico 
       add constraint fk_ordine_alcolico 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists ordine_alcolico 
       add constraint fk_ordine_alcolico_cantina 
       foreign key (cantina) 
       references cantina;

    alter table if exists ordine_alcolico 
       add constraint fk_ordine_alcolico_ordine 
       foreign key (id_ordine) 
       references ordine;

    alter table if exists ordine_alcolico 
       add constraint fk_status_ordine_alcolico 
       foreign key (status) 
       references status;

    alter table if exists ordine_box 
       add constraint fk_ordine_box 
       foreign key (id_box) 
       references box;

    alter table if exists ordine_box 
       add constraint fk_ordine_alcolico_cantina 
       foreign key (cantina) 
       references cantina;

    alter table if exists ordine_box 
       add constraint fk_ordine_alcolico_ordine 
       foreign key (id_ordine) 
       references ordine;

    alter table if exists ordine_box 
       add constraint fk_status_ordine_alcolico 
       foreign key (status) 
       references status;

    alter table if exists ordine_degustazione 
       add constraint fk_ordine_degustazione_cantina 
       foreign key (cantina) 
       references cantina;

    alter table if exists ordine_degustazione 
       add constraint fk_ordine_degustazione 
       foreign key (id_degustazione) 
       references degustazione;

    alter table if exists ordine_degustazione 
       add constraint fk_ordine_degustazione_ordine 
       foreign key (id_ordine) 
       references ordine;

    alter table if exists ordine_degustazione 
       add constraint fk_status_ordine_degustazione 
       foreign key (status) 
       references status;

    alter table if exists prenotazione_degustazione 
       add constraint fk_ordine_alcolico_cantina 
       foreign key (cantina) 
       references cantina;

    alter table if exists prenotazione_degustazione 
       add constraint fk_ordine_degustazione 
       foreign key (id_degustazione) 
       references degustazione;

    alter table if exists prenotazione_degustazione 
       add constraint fk_ordine_alcolico_ordine 
       foreign key (id_ordine) 
       references ordine;

    alter table if exists prenotazione_degustazione 
       add constraint fk_status_ordine_alcolico 
       foreign key (status) 
       references status;

    alter table if exists prodotto_alcolico 
       add constraint fk_prodotto_alcolico 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists prodotto_alcolico 
       add constraint fk_prodotto_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists prodotto_alcolico 
       add constraint fk_prodotto_carrello 
       foreign key (id_carrello) 
       references carrello;

    alter table if exists prodotto_box 
       add constraint fk_prodotto_box 
       foreign key (id_box) 
       references box;

    alter table if exists prodotto_box 
       add constraint fk_prodotto_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists prodotto_box 
       add constraint fk_prodotto_carrello 
       foreign key (id_carrello) 
       references carrello;

    alter table if exists prodotto_degustazione 
       add constraint fk_prodotto_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists prodotto_degustazione 
       add constraint fk_prodotto_carrello 
       foreign key (id_carrello) 
       references carrello;

    alter table if exists prodotto_degustazione 
       add constraint fk_prodotto_degustazione 
       foreign key (id_degustazione) 
       references degustazione;

    alter table if exists rating_alcolico 
       add constraint fk_rating_alcolico 
       foreign key (id_alcolico) 
       references alcolico;

    alter table if exists rating_alcolico 
       add constraint fk_rating_cantina 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists rating_alcolico 
       add constraint fk_rating_alcolico_utente 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists rating_cantina 
       add constraint fk_cantina_rating 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists rating_cantina 
       add constraint fk_rating_alcolico_utente 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists spedizione_alcolico 
       add constraint FK4fumiy82ibpvyhlt5pf4x3237 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists spedizione_alcolico 
       add constraint FK3k9hot3ra92o46r4s26u89l8 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists spedizione_alcolico 
       add constraint fk_spedizione_ordine_alcolico 
       foreign key (id_ordine_alcolico) 
       references ordine_alcolico;

    alter table if exists spedizione_alcolico 
       add constraint fk_status_ordine 
       foreign key (status) 
       references status;

    alter table if exists spedizione_box 
       add constraint FKtm9ier84fy9iix8kn61eohk5l 
       foreign key (id_cantina) 
       references cantina;

    alter table if exists spedizione_box 
       add constraint FKs1qmur4y1mdq2cxcfjx3wl5v0 
       foreign key (id_cliente) 
       references cliente;

    alter table if exists spedizione_box 
       add constraint fk_status_ordine 
       foreign key (status) 
       references status;

    alter table if exists utente 
       add constraint fk_utente_ruolo 
       foreign key (id_ruolo) 
       references role;

    alter table if exists venditore 
       add constraint fk_utente_venditore 
       foreign key (id_utente) 
       references utente;
